---
- hosts: localhost # play book execute locally in jenkins machine
  become: yes
  become_method: sudo
  tasks:
    - name: Install boto3
      pip:
        name: boto3
        state: present
    - name: create S3 bucket
      aws_s3:
        bucket: madhu-tf-123
        mode: create
        region: us-east-1
