---
- hosts: localhost
  become: yes
  become_method: sudo
  vars:
    state: present
    s3_bucket: madhu-tf-123
    key: "Jenkins/terraform.tfstate"
    region: us-east-1
    app_env: dev
  tasks:
    - name: Run Terraform Scripts
      terraform:
        project_path: "./"
        state: "{{ state }}"
        backend_config:
          region: "{{region}}"
          bucket: "{{s3_bucket}}"
          key: "{{key}}"    
        variables_file: "{{app_env}}.tfvars"
        workspace: "{{app_env}}"

    